# Site settings
title: Rifqi Fardi Pradhana
description: 'An Android Developer, Mobile Product Enthusiast'
url: 'https://about.me/rifqifardi'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Rifqi Fardi Pradhana'
  email: rifqifardi@gmail.com
  twitter_username: jboxxpradhana
  facebook_username: rifqifardi
  github_username:  jboxx
  linkedin_username:  rifqifardi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
